services:
  # Databases
  credentials_db:
    image: mysql
    container_name: credentials_db
    environment:
      MYSQL_DATABASE: credentials_db
      MYSQL_USER: credentials_user
      MYSQL_PASSWORD: credentials_pass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "4000:3306"
    volumes:
      - credentials_data:/var/lib/mysql
    networks:
      - energy_management_network
    restart: always

  users_db:
    image: mysql
    container_name: users_db
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: users_user
      MYSQL_PASSWORD: users_pass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "4001:3306"
    volumes:
      - users_data:/var/lib/mysql
    networks:
      - energy_management_network
    restart: always

  devices_db:
    image: mysql
    container_name: devices_db
    environment:
      MYSQL_DATABASE: devices_db
      MYSQL_USER: devices_user
      MYSQL_PASSWORD: devices_pass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "4002:3306"
    volumes:
      - devices_data:/var/lib/mysql
    networks:
      - energy_management_network
    restart: always

  # Backend Services
  authorization-service:
    build: ./backend/authorization-service
    container_name: authorization-service
    ports:
      - "8083:8080"
    environment:
      DB_HOST: credentials_db
      DB_USER: credentials_user
      DB_PASS: credentials_pass
      DB_NAME: credentials_db
    depends_on:
      - credentials_db
    networks:
      - energy_management_network
    restart: always

  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      DB_HOST: users_db
      DB_USER: users_user
      DB_PASS: users_pass
      DB_NAME: users_db
    depends_on:
      - users_db
    networks:
      - energy_management_network
    restart: always

  device-service:
    build: ./backend/device-service
    container_name: device-service
    ports:
      - "8082:8080"
    environment:
      DB_HOST: devices_db
      DB_USER: devices_user
      DB_PASS: devices_pass
      DB_NAME: devices_db
    depends_on:
      - devices_db
    networks:
      - energy_management_network
    restart: always

volumes:
  credentials_data:
  users_data:
  devices_data:

networks:
  energy_management_network:
    external: true
