spring:
  application:
    name: api-gateway

  jwt:
    secret: my_jwt_very_very_secret_key_for_jwt_token_generation

server:
  port: 8080

logging:
  level:
    com.vio.api_gateway: DEBUG
    org.springframework.security: DEBUG